#!/bin/bash
# | ----------------------------------------------------------------------------
# | Application
# | ----------------------------------------------------------------------------
# App Name
APP='API Ai Solutions'
# Container TAG
DOCKERNAME=ai-solution

function_exists() {
  declare -f -F $1 > /dev/null
  return $?
}
printf ""

# | ----------------------------------------------------------------------------
# | Cores
# | ----------------------------------------------------------------------------
RED='\033[0;31m'
GRAY='\033[0;36m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # RESET COR

function install() {
  docker exec -it $DOCKERNAME-app "$@"
}

function build() {
  docker compose build
}

# | ----------------------------------------------------------------------------
# | Start Dev com logs
# | ----------------------------------------------------------------------------
function dev() {
  docker compose up $1;
}


# | ----------------------------------------------------------------------------
# | Start Dev
# | ----------------------------------------------------------------------------
function start() {
  docker compose up -d $1;
}

# | ----------------------------------------------------------------------------
# | Start prod
# | ----------------------------------------------------------------------------
function prod() {
  docker compose up -d --build $1;
}

# | ----------------------------------------------------------------------------
# | Stop
# | ----------------------------------------------------------------------------
function stop() {
  docker compose down
}

# | ----------------------------------------------------------------------------
# | Removes service containers
# | ----------------------------------------------------------------------------
function prune() {
  docker compose rm --force --stop -v
}

# | ----------------------------------------------------------------------------
# | Restart
# | ----------------------------------------------------------------------------
function restart() {
  case "$1" in
    app) docker restart $DOCKERNAME-app
      ;;
    db) docker restart $DOCKERNAME-db
      ;;
    all) stop; start
      ;;
    *)
      echo -e "${GRAY}Informe o container que deseja reniciar:${NC}"
      echo ""
      echo -e " ${GRAY}./app ${YELLOW}restart ${LGREEN}i${NC}"
      echo -e " ${GRAY}./app ${YELLOW}restart ${LGREEN}db${NC}"
      echo ""
      echo -e "${GRAY} Todos os containers${NC}"
      echo -e " ${GRAY}./app ${YELLOW}restart ${LGREEN}all${NC}"
      exit 0
     ;;
  esac
}

# | ----------------------------------------------------------------------------
# | Bash Commands
# | ----------------------------------------------------------------------------
function sh() {
  case "$1" in
    app) docker exec -ti $DOCKERNAME-app sh $2
     ;;
    db) docker exec -ti $DOCKERNAME-db sh $2
     ;;
    -h|--help)
      echo -e "${GRAY}Informe o container que deseja acessar:${NC}"
      echo -e " ${GRAY}./app ${YELLOW}sh ${LGREEN}app${NC}"
      echo -e " ${GRAY}./app ${YELLOW}sh ${LGREEN}db${NC}"
      exit 0
     ;;
    *)
      echo -e "${GRAY}Informe o container que deseja acessar:${NC}"
      echo -e " ${GRAY}./app ${YELLOW}sh ${LGREEN}app${NC}"
      echo -e " ${GRAY}./app ${YELLOW}sh ${LGREEN}db${NC}"
      exit 0
     ;;
  esac
}

# | ----------------------------------------------------------------------------
# | Test
# | ----------------------------------------------------------------------------
function run_test() {
  sh test
}


# | ----------------------------------------------------------------------------
# | Recreate
# | ----------------------------------------------------------------------------
function recreate() {
  prune
  start
}

# if [ "$UID" -ne 0 ]
#   then echo "Please run as root"
#   exitadd packageart | sh app ou db | yarn"
#   exit
# fi

# | ----------------------------------------------------------------------------
# | Switch case commands
# | ----------------------------------------------------------------------------
case "$1" in
  php) function_exists install && install "$@"
    ;;
  prune)  function_exists prune && prune $2
    ;;
  dev)  function_exists dev && dev $2
      ;;
  build)  function_exists build && build
      ;;
  restart)  function_exists restart && restart $2
    ;;
  stop)  function_exists stop && stop $2
    ;;
  recreate) function_exists recreate && recreate
    ;;
  sh) function_exists sh && sh $2
    ;;
  -h|--help)
    echo -e "${GRAY}Seja bem vindo ao${NC} $APP"
    echo " "
    echo -e "${GRAY}./app ${YELLOW}[options] ${LGREEN}[arguments]${NC}"
    echo " "
    echo -e "${LGREEN}options:${NC}"
    echo -e "${YELLOW}  php artisan ${LGREEN} command ${NC}"
    echo -e "${YELLOW}  prune ${RED}- DOCKER${NC}"
    echo -e "${YELLOW}  restart ${RED}- DOCKER${NC}"
    echo -e "${YELLOW}  recreate ${RED}- DOCKER${NC}"
    echo -e "${LGREEN}  -h, --help${NC}"
    exit 0
    ;;
  *)
    echo "Informe commando:"
    echo -e "${LGREEN}  -h|--help${NC}              ${YELLOW}Mostrar ajuda${NC}"
    ;;
esac
